### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by morenogiudici** [horaciosystem/stopwatch#1]
Hi , if i run this component on the device after take more than 4 lap , is incredibly slow ! Where is the bottle neck?

**Comment by horaciosystem** [comment]
Hi @morenogiudici, I solved this problem. If you try again you'll realize that.

Where is the bottle neck?
The problem was in the fact that the **reconciliation process** of all parts of the app was happening in each 30 milliseconds, although only the timer needs to re-render with this frequency.

Then to solve this unnecessary computation:
1. We need to split the parts of the app in separated components where each one has its own render method. 
2. We need to say to react if is necessary or not to update the component, and the way we can do that is using the **shouldComponentFunction** function.

> shouldComponentUpdate, which is triggered before the re-rendering process starts (virtual DOM comparison and possible eventual DOM reconciliation), giving the developer the ability to short circuit this process. The default implementation of this function returns true, leaving React to perform the update

https://facebook.github.io/react/docs/advanced-performance.html#avoiding-reconciling-the-dom
